require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
AllCops:
  NewCops: enable
Rails/FilePath:
  EnforcedStyle: arguments
Style/Documentation:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
  CountAsOne:
    - array
    - hash
RSpec/MultipleExpectations:
  Max: 3
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
